export default {
    SET_SEARCH_STRING: 'SET_SEARCH_STRING',
    GET_LIST_REQUEST_START: 'GET_LIST_REQUEST_START',
    GET_LIST_REQUEST_COMPLETED: 'GET_LIST_REQUEST_COMPLETED',
    GET_LIST_REQUEST_ERROR: 'GET_LIST_REQUEST_ERROR'
};
